/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val name = "Lucas"
    var age = 25
    val imLearningKotlin = true

    println(name)
    println(age)
    println(imLearningKotlin)

    val city: String = "BsAs"
    val temperature: Double = 4.5
    val hasCoffee: Boolean = false
    val initial: Char = 'L'

    println(city)
    println(temperature)
    println(hasCoffee)
    println(initial)

    var plusOne = 1

    println(plusOne)

    plusOne = 2

    println(plusOne)
    /*Se utiliza var debido a que es un valor que tiene o puede mutar en el futuro,
    a diferencia de val que es un valor que permanece igual */
}
